### ISSUE TITLE
job_title_normalizer

### ISSUE THREAD

**Issue by yerrochdi** [eddietheeagle1/career_path_recommendation#1]
Hello,
I retrieved the project to test, except that I can not find the data (job_title_normalizer) that the read_data.py must retrieve.
Could you tell me where I can find or download the data.
Thanks for your help
Yassine

**Comment by eddiepease** [comment]
Hi,
I'm afraid this normalizer is propietary code for the company who provided the data and so I can't release it / don't have access to it any more. You would have to write you own function to normalize job titles to get meaningful results from the code in this repo.

**Comment by yerrochdi** [comment]
thank you
